matrix:
  include:
    # Jessie containers
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=jessie NODE=10
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=jessie NODE=8
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=jessie NODE=6

    # Alpine containers
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=alpine NODE=10
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=alpine NODE=8
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=alpine NODE=6

    # OSX builds
    - os: osx
      language: node_js
      node_js: 10
    - os: osx
      language: node_js
      node_js: 8
    - os: osx
      language: node_js
      node_js: 6

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      docker run -dt --name build -e PREBUILD_TOKEN=$PREBUILD_TOKEN -v $TRAVIS_BUILD_DIR:/src node:$NODE-$OS
      docker exec build sh -c "apk add libtool"
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      npm i
    else
      docker exec build sh -c "cd /src && npm i"
    fi

test:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      npm test
    else
      docker exec build sh -c "cd /src && npm test"
    fi

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      npm run coverage
    else
      docker exec build sh -c "cd /src && npm run coverage"
    fi
