matrix:
  include:
    # Jessie containers
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=jessie NODE=10
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=jessie NODE=8
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=jessie NODE=6

    # Alpine containers
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=alpine NODE=10
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=alpine NODE=8
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=alpine NODE=6

    # Jessie arm32v6 containers
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=jessie NODE=10 ARCH=arm32v6
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=jessie NODE=8 ARCH=arm32v6
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=jessie NODE=6 ARCH=arm32v6

    # Alpine containers
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=alpine NODE=10 ARCH=arm32v6
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=alpine NODE=8 ARCH=arm32v6
    - os: linux
      language: bash
      sudo: true
      services:
        - docker
      env: OS=alpine NODE=6 ARCH=arm32v6

    # OSX builds
    - os: osx
      language: node_js
      node_js: 10
    - os: osx
      language: node_js
      node_js: 8
    - os: osx
      language: node_js
      node_js: 6

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      if [ ! -z "$ARCH" ]
      then
        NODE="$ARCH/$NODE"
      fi

      docker run -dt --name build -e PREBUILD_TOKEN=$PREBUILD_TOKEN -v $TRAVIS_BUILD_DIR:/src node:$NODE-$OS

      if [[ "$OS" == "alpine" ]]
      then
        docker exec -t build sh -c "apk add --no-cache build-base libtool autoconf automake python linux-headers"
      fi

      if [[ "$OS" == "jessie" ]]
      then
        docker exec -t build sh -c "apt update"
        docker exec -t build sh -c "apt install -y build-essential libtool autoconf automake python"
      fi
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      npm i
    else
      docker exec -t build sh -c "cd /src && npm i && ./node_modules/.bin/node-gyp rebuild"
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      npm test
    else
      docker exec -t build sh -c "cd /src && npm test"
    fi

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      npm run coverage
    else
      docker exec -t build sh -c "cd /src && npm run coverage"
    fi
